services:
  - type: web_service
    name: luxury-haven-client
    env: node
    region: oregon
    branch: main
    root: Client/server
    buildCommand: cd ../.. && npm install --prefix shared && cd Client/server && npm install
    startCommand: npm start

  - type: web_service
    name: luxury-haven-admin
    env: node
    region: oregon
    branch: main
    root: admin/server
    buildCommand: cd ../.. && npm install --prefix shared && cd admin/server && npm install
    startCommand: npm start
